name: Build/release

# Only run the workflow when a new tag is found
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@master
        with:
          github_token: ${{ secrets.github_token }}
