name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Build and Publish
        run: |
          node -v
          sudo snap install snapcraft --classic
          sudo npm i -g electron --unsafe-perm=true --allow-root
          sudo npm i -g electron-builder --unsafe-perm=true --allow-root
          sudo npm i --unsafe-perm=true --allow-root
          npm run dist
          set -x
          assets=()
          for asset in ./dist/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
