name: Create Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # - name: Install Snapcraft
      #   # uses: samuelmeuli/action-snapcraft@v1
      #   # Only install Snapcraft on Ubuntu
      #   if: startsWith(matrix.os, 'ubuntu')
      #   run: sudo snap install snapcraft --classic
      #   # with:
      #     # Log in to Snap Store
      #     # snapcraft_token: ${{ secrets.snapcraft_token }}

      # - name: Prepare for app notarization
      #   if: startsWith(matrix.os, 'macos')
      #   # Import Apple API key for app notarization on macOS
      #   run: |
      #     mkdir -p ~/private_keys/
      #     echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }} # Automatically generated
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # env:
        #   # macOS notarization API key
        #   API_KEY_ID: ${{ secrets.API_KEY_ID }}
        #   API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
